### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by CreativeWolf** [cedced19/pifm-browser#1]
Hi,

Getting the following Error 

[cw@nodester dist]$ node pifm-browser.js
/home/cw/pifm-browser/dist/lib/launch.js:18
    exec(pifm, [zik.uri, config.audio.freq, config.audio.rate], null, function
                   ^
TypeError: Cannot read property 'uri' of undefined
    at set (/home/cw/pifm-browser/dist/lib/launch.js:18:20)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:26:9)
    at EventEmitter.<anonymous> (/home/cw/pifm-browser/dist/lib/launch.js:34:5)
    at EventEmitter.emit (events.js:107:17)
    at /home/cw/pifm-browser/dist/pifm-browser.js:69:10
    at /home/cw/pifm-browser/dist/node_modules/hapi/lib/server.js:180:24
    at done (/home/cw/pifm-browser/dist/node_modules/hapi/node_modules/items/lib/index.js:30:25)
    at Server.finalize (/home/cw/pifm-browser/dist/node_modules/hapi/lib/connection.js:166:9)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:129:20)

Please help...

Thanks

CreativeWolf

**Comment by cedced19** [comment]
Did you put some music in the dist folder?
The music must be in wav, in mono, and in the same rate as your configuration file.
Or maybe do:

```
cd ./lib
chmod 777 pifm
```

I use daily [pifm-node](https://github.com/cedced19/pifm-node), it is the same software without the web interface.
I have no time this morning to try to reproduce this error but I will test it tonight.

**Comment by CreativeWolf** [comment]
Hi,

I used a mp3 file, now used a mono wav file in the same rate as the config file.

Here is the error I'm getting now...

[cw@nodester dist]$ node pifm-browser.js
Server running at
  => http://localhost:7775
CTRL + C to shutdown
/home/cw/pifm-browser/dist/lib/launch.js:24
    var number = Math.floor(Math.random() \* list.length);
                                 ^
RangeError: Maximum call stack size exceeded
    at imul (native)
    at Object.random (native)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:24:34)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)
    at random (/home/cw/pifm-browser/dist/lib/launch.js:28:9)

Thanks

CreativeWolf

**Comment by CreativeWolf** [comment]
Heya,

My bad, ran it using sudo and it's playing but I think there is some issue with the rate. I tried converting a song and now it works!

This is cool and appreciate your help and support with my learning :)

Cheers

CreativeWolf

**Comment by cedced19** [comment]
Great!

Thank you of used this software!

Cédric
